=== AlexisThach/DodgeBlock/data/xsd/joueur.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/player"
           xmlns:db="http://www.univ-grenoble-alpes.fr/l3miage/player"
           elementFormDefault="qualified">

    <xs:element name="players">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="player" type="db:Player" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Player">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="posX" type="xs:double"/>
            <xs:element name="posY" type="xs:double"/>
            <xs:element name="speed" type="db:Speed"/>
            <xs:element name="parties" type="db:Parties"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Définition du type complexe "Parties" -->
    <xs:complexType name="Parties">
        <xs:sequence>
            <!-- Liste de parties -->
            <xs:element name="partie" type="db:Partie" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Définition du type complexe "Partie" -->
    <xs:complexType name="Partie">
        <xs:sequence>
            <xs:element name="score" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="date" type="xs:date"/>
    </xs:complexType>

    <xs:simpleType name="Speed">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== AlexisThach/DodgeBlock/data/xml/joueur.xml
<?xml version="1.0" encoding="UTF-8"?>
<players xmlns="http://www.univ-grenoble-alpes.fr/l3miage/dodgeblock"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/dodgeblock ../xsd/joueur.xsd">
    <player>
        <nom>Swindar</nom>
        <posX>18.0</posX>
        <posY>10.2</posY>
        <speed>3.0</speed>
        <parties>
            <partie date="2024-12-05">
                <score>180</score>
            </partie>
            <partie date="2024-12-08">
                <score>220</score>
            </partie>
            <partie date="2024-12-08">
                <score>170</score>
            </partie>
            <partie date="2024-12-08">
                <score>200</score>
            </partie>
        </parties>
    </player>
    <player>
        <nom>Ahyd</nom>
        <posX>18.0</posX>
        <posY>10.2</posY>
        <speed>3.0</speed>
        <parties>
            <partie date="2024-12-05">
                <score>300</score>
            </partie>
            <partie date="2024-12-08">
                <score>210</score>
            </partie>
            <partie date="2024-12-08">
                <score>140</score>
            </partie>
        </parties>
    </player>
</players>
