=== AlexisThach/DodgeBlock/data/xsd/sauvegarde.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/dodgeblock"
           xmlns:sa="http://www.univ-grenoble-alpes.fr/l3miage/dodgeblock"
           elementFormDefault="qualified">

    <!-- Élément racine -->
    <xs:element name="sauvegarde" type="sa:Sauvegarde"/>
        
        <xs:complexType name="Sauvegarde">
            <xs:sequence>
                <xs:element name="general" type="sa:General" />
                <xs:element name="player" type="sa:Player" />
                <xs:element name="etat-partie" type="sa:EtatPartie" />
            </xs:sequence>
        </xs:complexType>

    <xs:complexType name="General">
        <xs:sequence>
            <xs:element name="score" type="sa:PositiveInteger" />
            <xs:element name="saveDate" type="xs:date" />
            <xs:element name="difficultyLevel" type="sa:PositiveInteger" />
        </xs:sequence>
    </xs:complexType>

    <!-- Section Player -->
    <xs:complexType name="Player">
        <xs:sequence>
            <xs:element name="position" type="sa:Position"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Section GameState -->
    <xs:complexType name="EtatPartie">
        <xs:sequence>
            <xs:element name="blocks" type="sa:ListeBlocks" />
            <xs:element name="pouvoirs" type="sa:ListePouvoirs" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Position">
        <xs:sequence>
            <xs:element name="X" type="xs:int"/>
            <xs:element name="Y" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Liste d'Obstacles -->
    <xs:complexType name="ListeBlocks">
        <xs:sequence>
            <xs:element name="block" type="sa:BlockType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BlockType">
        <xs:sequence>
            <xs:element name="position" type="sa:Position" />
            <xs:element name="speed" type="sa:PositiveInteger" />
        </xs:sequence>
    </xs:complexType>

    <!-- Liste de PowerUps -->
    <xs:complexType name="ListePouvoirs">
        <xs:sequence>
            <xs:element name="pouvoir" type="sa:PouvoirType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PouvoirType">
        <xs:sequence>
            <xs:element name="type" type="xs:string" />
            <xs:element name="duree" type="sa:PositiveInteger" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="PositiveInteger">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== AlexisThach/DodgeBlock/data/xml/sauvegarde.xml
<?xml version="1.0" encoding="UTF-8"?>
<sauvegarde xmlns="http://www.univ-grenoble-alpes.fr/l3miage/dodgeblock"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/dodgeblock  ../xsd/sauvegarde.xsd">

    <general>
        <score>50</score>
        <saveDate>2024-11-29</saveDate>
        <difficultyLevel>1</difficultyLevel>
    </general>

    <player>
        <position>
            <X>500</X>
            <Y>300</Y>
        </position>
    </player>

    <etat-partie>
        <blocks>
            <block>
                <position>
                    <X>7</X>
                    <Y>12</Y>
                </position>
                <speed>2</speed>
            </block>
            <block>
                <position>
                    <X>6</X>
                    <Y>8</Y>
                </position>
                <speed>4</speed>
            </block>
        </blocks>
        <pouvoirs>
            <pouvoir>
                <type>Shield</type>
                <duree>10</duree>
            </pouvoir>
            <pouvoir>
                <type>DoubleScore</type>
                <duree>5</duree>
            </pouvoir>
        </pouvoirs>
    </etat-partie>

</sauvegarde>
